postsubmits:
  kubesphere/s2ioperator:
  - name: test-postsubmit
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  kubesphere/s2ioperator:
  - name: test-presubmit
    always_run: true
    skip_report: false
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
tide:
  merge_method:
    kubesphere/s2ioperator: squash
    kubesphere/porter: squash
    kubesphere/s2irun: squash
    yunify/qingcloud-cloud-controller-manager: squash
    yunify/hostnic-cni: squash
  target_url: http://139.198.120.205:8080/tide
  queries:
  - repos:
    - timestamp-nginx/nginx-project
    - yunify/qingcloud-csi
    - yunify/qingstor-csi
    - QingCloudAppcenter/QKE
    - kubesphere-test/prow-tutorial
    - kubesphere/s2ioperator
    - kubesphere/porter
    - yunify/qingcloud-cloud-controller-manager
    - yunify/hostnic-cni
    - kubesphere/kubesphere
    - kubesphere/s2irun
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-ok-to-test
    - needs-rebase

  context_options:
    # Use branch protection options to define required and optional contexts
    from-branch-protection: true
    # Treat unknown contexts as optional
    skip-unknown-contexts: true
    orgs:
      org:
        required-contexts:
        - "check-required-for-all-repos"
        repos:
          repo:
            required-contexts:
             - "check-required-for-all-branches"
            branches:
              branch:
                from-branch-protection: false
                required-contexts:
                - "required_test"
                optional-contexts:
                - "optional_test"